# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'probniy.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1240, 442)
        MainWindow.setMouseTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1221, 411))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.b_checkCert = QtWidgets.QPushButton(self.tab_3)
        self.b_checkCert.setGeometry(QtCore.QRect(995, 80, 205, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_checkCert.setFont(font)
        self.b_checkCert.setCheckable(False)
        self.b_checkCert.setAutoRepeat(False)
        self.b_checkCert.setAutoExclusive(False)
        self.b_checkCert.setObjectName("b_checkCert")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(0, 54, 110, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(0, 32, 110, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.storeType = QtWidgets.QComboBox(self.tab_3)
        self.storeType.setGeometry(QtCore.QRect(120, 5, 200, 20))
        self.storeType.setMouseTracking(False)
        self.storeType.setAcceptDrops(False)
        self.storeType.setEditable(True)
        self.storeType.setObjectName("storeType")
        self.storeType.addItem("")
        self.storeType.addItem("")
        self.storeType.addItem("")
        self.storeType.addItem("")
        self.storeType.addItem("")
        self.storeType.addItem("")
        self.storeType.addItem("")
        self.selectKey = QtWidgets.QToolButton(self.tab_3)
        self.selectKey.setGeometry(QtCore.QRect(295, 53, 25, 20))
        self.selectKey.setObjectName("selectKey")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, 0, 110, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(138, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setIndent(-1)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.keyPath = QtWidgets.QLineEdit(self.tab_3)
        self.keyPath.setGeometry(QtCore.QRect(120, 53, 170, 20))
        self.keyPath.setObjectName("keyPath")
        self.textBOX1 = QtWidgets.QTextEdit(self.tab_3)
        self.textBOX1.setGeometry(QtCore.QRect(5, 80, 486, 211))
        self.textBOX1.setFrameShape(QtWidgets.QFrame.Box)
        self.textBOX1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBOX1.setObjectName("textBOX1")
        self.textBOX2 = QtWidgets.QTextEdit(self.tab_3)
        self.textBOX2.setGeometry(QtCore.QRect(500, 80, 486, 211))
        self.textBOX2.setAutoFillBackground(False)
        self.textBOX2.setFrameShape(QtWidgets.QFrame.Box)
        self.textBOX2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBOX2.setObjectName("textBOX2")
        self.textBOX3 = QtWidgets.QTextEdit(self.tab_3)
        self.textBOX3.setGeometry(QtCore.QRect(5, 300, 981, 81))
        self.textBOX3.setFrameShape(QtWidgets.QFrame.Box)
        self.textBOX3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBOX3.setObjectName("textBOX3")
        self.rb_OCSPURL = QtWidgets.QRadioButton(self.tab_3)
        self.rb_OCSPURL.setGeometry(QtCore.QRect(995, 29, 72, 17))
        self.rb_OCSPURL.setObjectName("rb_OCSPURL")
        self.CRLpath = QtWidgets.QLineEdit(self.tab_3)
        self.CRLpath.setGeometry(QtCore.QRect(1068, 50, 101, 20))
        self.CRLpath.setObjectName("CRLpath")
        self.selectCRL = QtWidgets.QToolButton(self.tab_3)
        self.selectCRL.setGeometry(QtCore.QRect(1175, 50, 25, 20))
        self.selectCRL.setObjectName("selectCRL")
        self.OCSPpath = QtWidgets.QLineEdit(self.tab_3)
        self.OCSPpath.setGeometry(QtCore.QRect(1068, 26, 131, 20))
        self.OCSPpath.setObjectName("OCSPpath")
        self.rb_CRL = QtWidgets.QRadioButton(self.tab_3)
        self.rb_CRL.setGeometry(QtCore.QRect(995, 53, 72, 17))
        self.rb_CRL.setObjectName("rb_CRL")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(1020, 5, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(1000, 110, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.layoutWidget_6 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_6.setGeometry(QtCore.QRect(1104, 130, 84, 65))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.rb_outBase64 = QtWidgets.QRadioButton(self.layoutWidget_6)
        self.rb_outBase64.setObjectName("rb_outBase64")
        self.verticalLayout_5.addWidget(self.rb_outBase64)
        self.rb_outPEM = QtWidgets.QRadioButton(self.layoutWidget_6)
        self.rb_outPEM.setObjectName("rb_outPEM")
        self.verticalLayout_5.addWidget(self.rb_outPEM)
        self.rb_outDER = QtWidgets.QRadioButton(self.layoutWidget_6)
        self.rb_outDER.setObjectName("rb_outDER")
        self.verticalLayout_5.addWidget(self.rb_outDER)
        self.cb_in2Base64 = QtWidgets.QCheckBox(self.tab_3)
        self.cb_in2Base64.setGeometry(QtCore.QRect(995, 205, 91, 17))
        self.cb_in2Base64.setObjectName("cb_in2Base64")
        self.cb_draftSign = QtWidgets.QCheckBox(self.tab_3)
        self.cb_draftSign.setGeometry(QtCore.QRect(995, 230, 211, 17))
        self.cb_draftSign.setObjectName("cb_draftSign")
        self.cb_detachedSign = QtWidgets.QCheckBox(self.tab_3)
        self.cb_detachedSign.setGeometry(QtCore.QRect(995, 250, 221, 17))
        self.cb_detachedSign.setObjectName("cb_detachedSign")
        self.cb_addTimeStamp = QtWidgets.QCheckBox(self.tab_3)
        self.cb_addTimeStamp.setGeometry(QtCore.QRect(995, 270, 221, 17))
        self.cb_addTimeStamp.setObjectName("cb_addTimeStamp")
        self.b_getTimeFromSign = QtWidgets.QPushButton(self.tab_3)
        self.b_getTimeFromSign.setGeometry(QtCore.QRect(995, 320, 205, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_getTimeFromSign.setFont(font)
        self.b_getTimeFromSign.setCheckable(False)
        self.b_getTimeFromSign.setAutoRepeat(False)
        self.b_getTimeFromSign.setAutoExclusive(False)
        self.b_getTimeFromSign.setObjectName("b_getTimeFromSign")
        self.b_clear = QtWidgets.QPushButton(self.tab_3)
        self.b_clear.setGeometry(QtCore.QRect(995, 350, 205, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_clear.setFont(font)
        self.b_clear.setCheckable(False)
        self.b_clear.setAutoRepeat(False)
        self.b_clear.setAutoExclusive(False)
        self.b_clear.setObjectName("b_clear")
        self.layoutWidget = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget.setGeometry(QtCore.QRect(330, 10, 656, 54))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.b_showCert = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_showCert.setFont(font)
        self.b_showCert.setCheckable(False)
        self.b_showCert.setAutoRepeat(False)
        self.b_showCert.setAutoExclusive(False)
        self.b_showCert.setObjectName("b_showCert")
        self.gridLayout.addWidget(self.b_showCert, 0, 0, 1, 1)
        self.b_signData = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_signData.setFont(font)
        self.b_signData.setCheckable(False)
        self.b_signData.setAutoRepeat(False)
        self.b_signData.setAutoExclusive(False)
        self.b_signData.setObjectName("b_signData")
        self.gridLayout.addWidget(self.b_signData, 0, 1, 1, 1)
        self.b_hashData = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_hashData.setFont(font)
        self.b_hashData.setCheckable(False)
        self.b_hashData.setAutoRepeat(False)
        self.b_hashData.setAutoExclusive(False)
        self.b_hashData.setObjectName("b_hashData")
        self.gridLayout.addWidget(self.b_hashData, 0, 2, 1, 1)
        self.b_signXML = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_signXML.setFont(font)
        self.b_signXML.setCheckable(False)
        self.b_signXML.setAutoRepeat(False)
        self.b_signXML.setAutoExclusive(False)
        self.b_signXML.setObjectName("b_signXML")
        self.gridLayout.addWidget(self.b_signXML, 0, 3, 1, 1)
        self.b_getCertFromCMS = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_getCertFromCMS.setFont(font)
        self.b_getCertFromCMS.setCheckable(False)
        self.b_getCertFromCMS.setAutoRepeat(False)
        self.b_getCertFromCMS.setAutoExclusive(False)
        self.b_getCertFromCMS.setObjectName("b_getCertFromCMS")
        self.gridLayout.addWidget(self.b_getCertFromCMS, 0, 4, 1, 1)
        self.b_infoCert = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_infoCert.setFont(font)
        self.b_infoCert.setCheckable(False)
        self.b_infoCert.setAutoRepeat(False)
        self.b_infoCert.setAutoExclusive(False)
        self.b_infoCert.setObjectName("b_infoCert")
        self.gridLayout.addWidget(self.b_infoCert, 1, 0, 1, 1)
        self.b_verifyData = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_verifyData.setFont(font)
        self.b_verifyData.setCheckable(False)
        self.b_verifyData.setAutoRepeat(False)
        self.b_verifyData.setAutoExclusive(False)
        self.b_verifyData.setObjectName("b_verifyData")
        self.gridLayout.addWidget(self.b_verifyData, 1, 1, 1, 1)
        self.b_verifyHashData = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_verifyHashData.setFont(font)
        self.b_verifyHashData.setCheckable(False)
        self.b_verifyHashData.setAutoRepeat(False)
        self.b_verifyHashData.setAutoExclusive(False)
        self.b_verifyHashData.setObjectName("b_verifyHashData")
        self.gridLayout.addWidget(self.b_verifyHashData, 1, 2, 1, 1)
        self.b_verifyXML = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_verifyXML.setFont(font)
        self.b_verifyXML.setCheckable(False)
        self.b_verifyXML.setAutoRepeat(False)
        self.b_verifyXML.setAutoExclusive(False)
        self.b_verifyXML.setObjectName("b_verifyXML")
        self.gridLayout.addWidget(self.b_verifyXML, 1, 3, 1, 1)
        self.b_getCertFromXML = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.b_getCertFromXML.setFont(font)
        self.b_getCertFromXML.setCheckable(False)
        self.b_getCertFromXML.setAutoRepeat(False)
        self.b_getCertFromXML.setAutoExclusive(False)
        self.b_getCertFromXML.setObjectName("b_getCertFromXML")
        self.gridLayout.addWidget(self.b_getCertFromXML, 1, 4, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(1000, 130, 84, 65))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rb_inBase64 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rb_inBase64.setObjectName("rb_inBase64")
        self.verticalLayout_4.addWidget(self.rb_inBase64)
        self.rb_inPEM = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rb_inPEM.setObjectName("rb_inPEM")
        self.verticalLayout_4.addWidget(self.rb_inPEM)
        self.rb_inDER = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rb_inDER.setObjectName("rb_inDER")
        self.verticalLayout_4.addWidget(self.rb_inDER)
        self.SignID = QtWidgets.QLineEdit(self.tab_3)
        self.SignID.setGeometry(QtCore.QRect(1104, 202, 39, 20))
        self.SignID.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SignID.setAlignment(QtCore.Qt.AlignCenter)
        self.SignID.setObjectName("SignID")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(1149, 204, 47, 13))
        self.label_4.setObjectName("label_4")
        self.pinCode = QtWidgets.QLineEdit(self.tab_3)
        self.pinCode.setGeometry(QtCore.QRect(120, 30, 200, 20))
        self.pinCode.setText("")
        self.pinCode.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pinCode.setPlaceholderText("")
        self.pinCode.setObjectName("pinCode")
        self.certAlias = QtWidgets.QComboBox(self.tab_3)
        self.certAlias.setEnabled(True)
        self.certAlias.setGeometry(QtCore.QRect(995, 290, 205, 22))
        self.certAlias.setEditable(True)
        self.certAlias.setObjectName("certAlias")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame = QtWidgets.QFrame(self.tab_4)
        self.frame.setGeometry(QtCore.QRect(10, 10, 311, 241))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(40, 10, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(20, 52, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(20, 84, 47, 13))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(20, 142, 47, 13))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(20, 172, 47, 13))
        self.label_13.setObjectName("label_13")
        self.adres = QtWidgets.QLineEdit(self.frame)
        self.adres.setGeometry(QtCore.QRect(70, 50, 190, 20))
        self.adres.setFrame(True)
        self.adres.setObjectName("adres")
        self.port = QtWidgets.QLineEdit(self.frame)
        self.port.setGeometry(QtCore.QRect(70, 82, 190, 20))
        self.port.setFrame(True)
        self.port.setObjectName("port")
        self.login = QtWidgets.QLineEdit(self.frame)
        self.login.setGeometry(QtCore.QRect(70, 140, 190, 20))
        self.login.setFrame(True)
        self.login.setObjectName("login")
        self.pass_line = QtWidgets.QLineEdit(self.frame)
        self.pass_line.setGeometry(QtCore.QRect(70, 172, 190, 20))
        self.pass_line.setFrame(True)
        self.pass_line.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.pass_line.setObjectName("pass_line")
        self.cb_proxy = QtWidgets.QCheckBox(self.frame)
        self.cb_proxy.setGeometry(QtCore.QRect(20, 110, 241, 17))
        self.cb_proxy.setObjectName("cb_proxy")
        self.b_save = QtWidgets.QPushButton(self.frame)
        self.b_save.setGeometry(QtCore.QRect(220, 210, 75, 23))
        self.b_save.setObjectName("b_save")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b_checkCert.setText(_translate("MainWindow", "Проверить сертификат"))
        self.label_3.setText(_translate("MainWindow", "Путь к ключу"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.storeType.setItemText(0, _translate("MainWindow", "Ничего не выбрано"))
        self.storeType.setItemText(1, _translate("MainWindow", "Файловая система - PKCS#12 (*.p12)"))
        self.storeType.setItemText(2, _translate("MainWindow", "Удостоверение личности гражданина РК (KZIDCard)"))
        self.storeType.setItemText(3, _translate("MainWindow", "Kaztoken"))
        self.storeType.setItemText(4, _translate("MainWindow", "eToken72K"))
        self.storeType.setItemText(5, _translate("MainWindow", "JaCarta"))
        self.storeType.setItemText(6, _translate("MainWindow", "Сертификат PEM (*.cer, *.crt, *.pem)"))
        self.selectKey.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Тип ключевого хранилища"))
        self.rb_OCSPURL.setText(_translate("MainWindow", "OCSP URL"))
        self.selectCRL.setText(_translate("MainWindow", "..."))
        self.OCSPpath.setText(_translate("MainWindow", "http://ocsp.pki.gov.kz/"))
        self.rb_CRL.setText(_translate("MainWindow", "CRL"))
        self.label_7.setText(_translate("MainWindow", "Тип проверки сертициката:"))
        self.label_8.setText(_translate("MainWindow", "Формат входных/выходных данных:"))
        self.rb_outBase64.setText(_translate("MainWindow", "OUT Base64"))
        self.rb_outPEM.setText(_translate("MainWindow", "OUT PEM"))
        self.rb_outDER.setText(_translate("MainWindow", "OUT DER"))
        self.cb_in2Base64.setText(_translate("MainWindow", "IN2 Base64"))
        self.cb_draftSign.setText(_translate("MainWindow", "Сырая подпись (V-Draft Sign, 0-CMS)"))
        self.cb_detachedSign.setText(_translate("MainWindow", "Подпись хранится отдельно от данных"))
        self.cb_addTimeStamp.setText(_translate("MainWindow", "Добавить метку времени в подпись"))
        self.b_getTimeFromSign.setText(_translate("MainWindow", "Получить время подписи"))
        self.b_clear.setText(_translate("MainWindow", "Очистить"))
        self.b_showCert.setText(_translate("MainWindow", "Показать сертификат"))
        self.b_signData.setText(_translate("MainWindow", "Подписать данные"))
        self.b_hashData.setText(_translate("MainWindow", "Хэшировать данные"))
        self.b_signXML.setText(_translate("MainWindow", "Подписать XML"))
        self.b_getCertFromCMS.setText(_translate("MainWindow", "Получить сертификат из CMS"))
        self.b_infoCert.setText(_translate("MainWindow", "Информация о сертификате"))
        self.b_verifyData.setText(_translate("MainWindow", "Проверить данные"))
        self.b_verifyHashData.setText(_translate("MainWindow", "Подписать ХЭШ-данные"))
        self.b_verifyXML.setText(_translate("MainWindow", "Проверить XML"))
        self.b_getCertFromXML.setText(_translate("MainWindow", "Получить сертицикат из XML"))
        self.rb_inBase64.setText(_translate("MainWindow", "IN Base64"))
        self.rb_inPEM.setText(_translate("MainWindow", "IN PEM"))
        self.rb_inDER.setText(_translate("MainWindow", "IN DER"))
        self.SignID.setText(_translate("MainWindow", "1"))
        self.label_4.setText(_translate("MainWindow", "Sign ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Подпись"))
        self.label_9.setText(_translate("MainWindow", "Настройка прокси:"))
        self.label_10.setText(_translate("MainWindow", "Адрес"))
        self.label_11.setText(_translate("MainWindow", "Порт"))
        self.label_12.setText(_translate("MainWindow", "Логин"))
        self.label_13.setText(_translate("MainWindow", "Пароль"))
        self.cb_proxy.setText(_translate("MainWindow", "Прокси-сервер требует авторизации"))
        self.b_save.setText(_translate("MainWindow", "Сохранить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Настройка"))

